# Travis CI script

language: c
compiler:
- clang
- gcc

sudo: false
dist: trusty

env:
- BOARD=ml605 EXAMPLES=yes SYSTEM_INTEGRATION=no APP=halcsd
- BOARD=afcv3 EXAMPLES=yes SYSTEM_INTEGRATION=no APP=halcsd
- BOARD=afcv3_1 EXAMPLES=yes SYSTEM_INTEGRATION=no APP=halcsd

matrix:
  include:
  - compiler: gcc
    env: GRADLE="installLibPcieDriver collectRpms" DEPLOY="yes"
  - compiler: clang
    env: GRADLE="installLibPcieDriver assemble"

addons:
  apt:
    packages:
    - uuid-dev
  sonarqube:
    token:
      secure: "AXQyy5C9NUv1aeIeVuLClBtLDkZsR4MDTFpIkzgrZX5fOVtVjyukeXfxk91GOtR76lGS5aX0WZLz+yMxsjFcGb49wigPSArZ91VE/UUPMZEIenjzObFdlz23a4GcfBtzTqzlChLNj3AaD80Jt9jUWXlLxTg+1p3FjWmmPS4Nu/VmtL9Nk5XdUwWNnptWWgmf0oL1n9ACRtpEhlBWd8HqzgxfGcT+WPo99TqFm/RZkngSMfgy9u4n1EBixxT7xVe0YVx1pke9hKCpHBMypLuARide/ZAcUf9OeuSgRlpa2+cY/Fn1P6MNfPGIaDbCZQ7PjN8CSJFjsGq+WpT3kNEw96+FHGU4z43eih1Cgo4q6XfezVkk5eLq7QQQVPGDN72VIj2oBAvXoWLxqpY5mA95Nw/rWWahsRScYap+gMHIDGpEwd54RvUMbZSgYTxLc74x6VCMW71JwB0UwUPt9UczVvUQirvPP7JtS4Th0WbFMAXPdOJE0l2F5/mBHbJyWPfD9PA5R/EYIpVkEG5kaZeYcBi0yqIXhW+yAlL6oiPNM28b0RNRkg8bsM0JZL7Vz/+b7+4rU4Ac4b47pCRWgnK6CpWL4C8FY9i0hzAyGq4SCoZPUEHY+Q8zMaGWnqcUePGsk/5bIAtu/Ot7OZcdF9HU3Pg0yeqDyXuyP4sG2q5Er3I="
    branches:
      - master
      - devel
      - sonarqube-integration

before_install:
- git submodule update --init --recursive

#   Build and check this project
script:
- ./ci_build.sh
- ./ci_scanner.sh

cache:
  directories:
    - '$HOME/.sonar/cache'

before_deploy:
- . ./ci_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "TMHoQQwZ4eHnnzfxoDEV15igEFpaVyYWVTN/Q583PtF15CLkbQpfEWDDgKZTMiUbuoeI3X+WPMb2F713wBB6MQ+yVKkRDfHKyIbpTWmwIht5isBnn8+eXuV53X1PzAPJXmzrbos5X3FNExV7eJqf1sldxiVmPyLKMssM+X4wG3+GIHPjxYd1dp/9v9d1uj2DZe1iApDezUxi2Oz3fdVZyx1O8KgyAoQ8uqXc3WDykGNXsJKJGMSFtpTGCyMI6etPZJRA0pn+zrGViYzsZnpv55whzAXGxXWsmo5OT6HvjrjKtiDDSyKLuNM7kqC3MoeYZ+2XGoYycoVMAlPdUKqMqrM/UVJ4ltYsJVb1ROSRpFmK17dEtZwQWLxNPkww/ixZeGFP47UUgdET+8ZDkvNC6ZM0VoMBvvoTKzrotQdM83DqDiGTyXDmgwWXzoqze02iYrV8UdmaX4JEvhMDJJGowzVipHy/VvPO6wRj5v8Achy6ntENM0wPYfQjanM+0pGJvsSHo/rZTP+OWOLtILKtcW7c3jMY/jlNq7jLc/WGEj3GZfUqgx8wN0ldCG0jO0n7OlZtmV5qUkqMNB3WunkFYEujaaCobTDScIjVx10UcXfUYT/iPmZr0Pt/8yBNyPHAORfStKNbVhgwzRZtDKzYKxaU9z2G6gAY9cFAViA8P3U="
  file_glob: true
  file: ${HALCS_DEPLOYMENT}
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: $DEPLOY = "yes"
