# Travis CI script

language: c
compiler:
- clang
- gcc

sudo: false

env:
- BOARD=ml605 EXAMPLES=yes LIBS_LINK=no APP=ebpm
- BOARD=afcv3 EXAMPLES=yes LIBS_LINK=no APP=ebpm
- BOARD=afcv3_1 EXAMPLES=yes LIBS_LINK=no APP=ebpm

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- git submodule update --init --recursive

#   Build and check this project
script:
- ./ci_build.sh
