# Travis CI script

language: c
compiler:
- clang
- gcc

sudo: false

env:
- BOARD=ml605 WITH_EXAMPLES=with_examples
- BOARD=afcv3 WITH_EXAMPLES=with_examples

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- git submodule update --init --recursive

#   Build and check this project
script:
- ./ci_build.sh
